version: '3.4'

services:
  rabbit:
      hostname: rabbit
      image: rabbitmq:3.11.1-management
      ports:
         - "5672:5672" 
         - "15672:15672"  
  postgres:
      image: postgres:13-alpine
      environment:
         - POSTGRES_PASSWORD=password
      ports:
         - "5432:5432"
  mongodb:
      image : mongo
      environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myPassword1
      volumes:
      - mongodb-data:/data/db
      ports:
      - 27017:27017
      restart: unless-stopped
  web:
      build:
        context: ./src
        dockerfile: ./Web/Web.API/Dockerfile
      ports:
        - "5000:5000"
      environment:
        - RABBIT_HOST=rabbit
        - RABBIT_LOGIN=guest
        - RABBIT_PASSWORD=guest
  shop:
      build:
        context: ./src
        dockerfile: ./Shop/Shop.Application/Dockerfile
      environment:
        - RABBIT_HOST=rabbit
        - RABBIT_LOGIN=guest
        - RABBIT_PASSWORD=guest
        - PrefetchCount=100
        - ConnectionStrings__POSTGRES=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=shop;Integrated Security=true;
        - ConnectionStrings__MongoDb=mongodb://root:myPassword1@mongodb:27017
  stock:
    build:
      context: ./src
      dockerfile: ./Stock/Stock.Application/Dockerfile
    environment:
      - RABBIT_HOST=rabbit
      - RABBIT_LOGIN=guest
      - RABBIT_PASSWORD=guest
      - PrefetchCount=100
      - ConnectionStrings__POSTGRES=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=stock;Integrated Security=true;
volumes:
 mongodb-data: