version: '3.4'

services:
  rabbit:
      hostname: rabbit
      image: rabbitmq:3.11.1-management
      ports:
         - "5672:5672" 
         - "15672:15672"  
  postgres:
      image: postgres:13-alpine
      environment:
         - POSTGRES_PASSWORD=password