version: '3.4'

services:
  rabbit:
      hostname: rabbit
      image: rabbitmq:3.11.1-management
      ports:
         - "5672:5672" 
         - "15672:15672"  
  postgres:
      image: postgres:13-alpine
      environment:
         - POSTGRES_PASSWORD=password
      ports:
         - "5432:5432"
  redis:
      image: redis:6.2-alpine
      restart: always
      ports:
         - "6379:6379"
      command: redis-server --requirepass myPassword1@
      volumes: 
         - redis:/data
volumes:
  redis:
    driver: local